### ISSUE TITLE
DocBook 5?

### ISSUE THREAD

**Issue by Zearin** [tLDP/LDP#3]
I’m a huge fan of DocBook, but never expected to find another docs project built on it.  So I’m feeling kind of gleeful to have found this repo. :)

Would there be an interest in converting to the (fully XML, rather than SGML) DocBook 5?  

I believe I could help, if the desire is there.

**Comment by Fat-Zer** [comment]
If you are still interested I was told the migration will be apreciated before pull-request #1. But the project seems to be quite dead...

**Comment by Zearin** [comment]
> If you are still interested I was told the migration will be apreciated before pull-request #1. But the project seems to be quite dead...

@Fat-Zer Yes, that’s why I said “if the desire is there”.  I’m still open to doing the work, but I would want to make sure that my work actually had an impact before putting the time in…

**Comment by ser** [comment]
I can fully support you, unfortunately a member who was responsible for rendering engine resigned and we are stuck on it :(

**Comment by mkomarinski** [comment]
We seem to be resurrecting.  I think there is interest in moving to DocBook 5, but there's a lot of other things that we'd like to get done first, including a review of all the documentation that already exists and getting the submission/acceptance/rendering processes updated.  Updating the LDP Author Guide to 5 is on my wish list, but there's a lot of link rot and other updates I'd like to get to first.

**Comment by martin-a-brown** [comment]
Zearin,

We have utterly basic support for DocBook 5.0, finally.  If you are interested in contributing, we certainly need some sort of help on the styling.  If you compare a DocBook XML 4.x document output with a DocBook 5.0 output, it's clear that the DocBook 4.x outputs look a bit nicer (at least the HTML).

We have made zero customizations to the DocBook 5 stylesheets, though it would be nice to add a customization layer, as we hope to support more DocBook 5 in the future.

Here's how we run the DocBook 5 (yes, it's a shell script generated from Python):

  https://github.com/tLDP/python-tldp/blob/master/tldp/doctypes/docbook5xml.py

See below, an example of a generate shell script (renamed with .txt so that github.com interface will allow it be appended to this issue).

Given that we only have the most very basic support for DocBook 5.0 at this point, we'd be happy for recommendations and/or help.

N.B. We have only two documents in DocBook 5.0 format at this point, the Assembly-HOWTO and the Package-Management-Basics-HOWTO.

Also, I realize that you posted your original question a year ago, so I'm going to close this issue.  If you remain interested, please join us at discuss@en.tldp.org.

And, thank you very much for your interest,

-Martin


[sample-docbook5-process.txt](https://github.com/tLDP/LDP/files/196854/sample-docbook5-process.txt)
